### ISSUE TITLE
NetWatcher improvements

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#132]
This issue lists the upcomming tasks to improve the functionality of the `Netwatcher` (NW) for the semi-automated and fully-automated mode. 

A complete structure overview can be found here: [incentive-app-structure](https://github.com/hoprnet/ct-research/wiki/App-structure)

## Overview
In the incentive-app, the `Netwatcher`s are responsible for gathering peers in the network, along with their connection latency (received by pinging them). They transmit the detected list of available peers to the `Aggregator` via an HTTP POST request. Besides this, they must be able to listen to a queue that the `EconomicHandler` serves, open and close payment channels, and send messages according to the tasks in the queue.

## Tasks
 Task  | Description | Issue
 --- | --- | ---
Define the pace at which the NWs are gathering connected peers and transmitting their connected-peers-list to the `Aggregator` | Currently the NWs wake up every couple of seconds. Before deploying code to production, this delay needs to be defined. It relies on the performance of a hoprd node and the number of peers in the network. | #192  
Fully use the logger | The Logger is used sometimes, not everywhere. `print`s must be replaced by logging statements at least, plus add additional logging. | #170 
Open channels to connected peers | To send 1 HOP messages through a peer, a channel needs to be opened. A channel gets opened after a pong has been received. *Do we need a closing strategy?* | #189 
Observe the queue filled by the `EconomicHandler` | The incoming queue contains information for sending 1HOP messages. NWs need to be able to listen to that queue. | #190
Send 1 HOP messages through peers back to the host | Sending messages is already an endpoint of the API. Therefore, the queue needs to contain information about the peer and the amount of messages that must be sent | #191 

The following tasks should be done only if the ones above are finished.

 Task  | Description | Issue
 --- | --- | ---
Redirect failed tasks to an outgoing queue | When a NW is unable to complete a task and is the last possible NW for sending a message to the given peer, it should redirect the task to an outgoing queue (NW perspective). | Reported. See #206 
Create task for successful message delivery | When a message delivery is successful, a task should be created in the outgoing queue so that the `EconomicHandler` can store this information in the `rewardTable`. | Reported. See #206
Monitoring the xDAI balance of a NW | A NW needs xDai for transactions fees related to, for example, opening and closing of payment channels. Therefore, we need to monitor the xDAI balance of a given NW to manually fund them in case the nodes run out of funds. | #198
Communicate xDAI balance through POST request to the `Aggregator` | We must monitor the xDAI balance at any point in time. As the `Aggregator` already exposes some endpoints, it can be used for exposing NW's xDAI balances. Thus, the balance needs to be sent along with the detected peers. | #198 

## Definition of Done
- [x] Proper use of the Logger
- [x] Queues are used to send messages through a peer
- [x] xDai balance monitored
- [x] New functionalities' unittests passing
