### ISSUE TITLE
Aggregator/AggTrigger improvements

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#133]
This issue lists the upcomming tasks to improve the functionality of the `Aggregator` (AGG) and the `AggTrigger` (TRG) for the semi-automated and fully-automated mode. 

A complete structure overview can be found here: [incentive-app-structure](https://github.com/hoprnet/ct-research/wiki/App-structure)

## Overview
In the incentive-app, the `Aggregator` is responsible for gathering available peers detected by the `Netwatcher`s. The `Aggregator` is actually a `Sanic` web server exposing HTTP endpoints and the `Netwatcher`s transmit their lists of available peers to the `Aggregator` via HTTP POST requests. The `Aggregator` also exposes an endpoint for retrieving metrics (e.g. the length of the unique list gathered of peers).
Besides this, the `Aggregator` contains the logic of the NW-peer load balancing, and deals with writing to a database table the peer-NW pairs.

## Tasks
 Task  | Description | Issue
 --- | --- | ---
Proper use of the Logger | The Logger is used sometimes, not everywhere. `print`s must be replaced by logging statements at least, plus add additional logging. | #169 
[AGG] Expose `NetWatcher`s and AGG metrics through HTTP endpoints | For monitoring purposes, we need to define which metrics must be exposed through an (already existing) HTTP endpoint, and expose them. | #150 
[AGG] Use the GCP database | Currently we mock the postgreSQL database on our local machines. It can be changed now to using GCP's. | ✅
[TRG] Define the pace at which the TRG triggers the `Aggregator` | The TRG triggers the `Aggregator` to send the formatted peer-netwatcher pairs to the `metricTable`.  Currently, the TRG wakes-up every couple of seconds. Before deploying code into production, this delay needs to be defined. It relies on the `Netwatcher` pace. | Reported. See #206 

The following tasks are related to the fully automated mode, and should be done only if the ones above are finished.

 Task  | Description | Issue
 --- | --- | ---
[AGG] Add a required field in the POST request when receiving lists from `NetWatcher`s to store their xDAI balance for monitoring | `Netwatcher`s are already sending information through a POST request. Their xDAI balance should be transmitted too. This can be a separate process, with an independent pace, or within the already existing POST request. | #148 

## Definition of Done
- [x] [AGG/TRG] Proper use of the Logger
- [x] [AGG] Documented and implemented the feature to expose metrics
- [x] [AGG] Use the GCP database
- [x] [TRG] Pace choice documented and implemented
- [x] Unit tests of new features
