### ISSUE TITLE
DatabaseConnection improvements

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#134]
This issue lists the upcomming tasks to improve the functionality of the `DatabaseConnection` (EH) for the semi-automated and fully-automated mode. 

A complete structure overview can be found here: [incentive-app-structure](https://github.com/hoprnet/ct-research/wiki/App-structure)

## Overview
In the incentive-app, communication with a centralized database is crucial. We use two tables (same database): In the `metricsTable` the `Aggregator` writes metrics and the `EconomicHandler` reads them. We store the success rate of message delivery (and possibly other metrics) in the (`rewardTable`). 
We use the `psycopg2` Python library. This library allows us to execute commands on (postgre)SQL databases. For simplicity of usage, and because multiple parts of the app need to communicate with a database, the `DatabaseConnection` class has been implemented. It contains many useful methods, but still needs improvements.

## Tasks
 Task  | Description | Issue
 --- | --- | ---
Assign an informative name to the `rewardTable` | The name `rewardTable` was decided quickly as placeholder, but we need something more informative. | Reported. See #206 
Add a method to query all recent entries | For now, a method in the db class is available to query the last peer-nw pairs entries. For the `EconomicHandler`, we need a method to query all the entries instead of the most recent ones to reduce the variance in the queried peer set. | #146 
Fully use the logger | The Logger is used sometimes, not everywhere. `print`s must be replaced by logging statements at least, plus add additional logging. | #168 

The following tasks are related to the fully automated mode, and should be done only if the ones above are finished.

Task  | Description | Issue
 --- | --- | ---
Define the content of `rewardTable` | The `rewardTable` is going to be used to store the state of message delivery. The actual content and structure of the table (columns) is not yet defined. | Reported. See #206 

## Definition of Done
- [x] Ability to query most recent entries (newer than a given timestamp).
- [x] Proper use of the Logger
- [x] New functionalities' unittests passing
