### ISSUE TITLE
Subgraph implementation

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#135]
This issue lists the necessary steps to implement the subgraph for the safe smart contract (SSC).

A complete structure overview can be found here: [ct-app-structure](https://github.com/hoprnet/ct-research/wiki/App-structure)

## Overview
We need to program and deploy a subgraph that listens to the SSC in order to create a link between the `safe-address` of a user, `node-address` and the total amount of `wxHOPR` tokens that this user has staked in the SSC. 

## Expected Outcome 

```
query MyQuery {
  safes(first: 1) {
    registeredNodesInNetworkRegistry {
      node {
        id
      }
      safe {
        id
        balances {
          wxHoprBalance
        }
      }
    }
    registeredNodesInSafeRegistry {
      node {
        id
      }
      safe {
        id
        balances {
          wxHoprBalance
        }
      }
    }
  }
``` 

## Tasks
- [x] Setup the development environment for the subgraph (i.e. subgraph studio)  
- [x] Implement the subgraph and the logic to link safe-addresses, node-addresses, and wxHOPR stake. 
- [x] Implement the query in the ct-app #285
- [x] Deploy the subgraph in staging and production and make an endpoint available to query the results
