### ISSUE TITLE
EconomicHandler improvements

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#136]
This issue lists the upcoming tasks to improve the functionality of the `EconomicHandler` (EH) for the semi-automated and fully-automated mode. 

A complete structure overview can be found here: [incentive-app-structure](https://github.com/hoprnet/ct-research/wiki/App-structure)

## Overview

The implementation of the listed improvements will allow us to deploy the `ct-app` in a staging environment where we can test how the different parts of the app work together.
- Status Quo: The EH runs independently from the other parts of the `ct-app`.

## Tasks

 Task  | Description | Issue
 --- | --- | ---
Add communication logic for EH&rarr;DB | The EH should be able to read the peer list (including peer metrics) from the metrics table of the database. Furthermore, add logic to read the database if it contains at least **X** entires. The economic handler can only start if the Aggregator wrote at least once to the database. Currently, we mock the response from the metrics table of the database. | #223
Flexible budget splitting rule. | We should be able to split the total budget for a given period into any fraction to calculate expected rewards based on the fraction instead of the entire period budget. Note that this is important as expected rewards are used to generate tasks for `NetWatchers` . Currently, the entire budget for a given period of length $t$ is used to calculate the expected rewards for each node at each execution of the EH. | #194
Add logic to split the budget between automatic distribution and airdrop distribution. | Currently, the economic handler does not distinguish between the automatic and airdrop mode | #194
Split computation and saving to a`.csv` file  functionalities| For now, those two things are in the same method, tested at the time, even if they do completely different things. Include more information into the csv file | #158
Allow 1-to-many safe addresses-peerID links | Multiple peers may be linked to the same safe address. If the amount staked in the safe is the same for all peerID, distribution model would be biased | #167
Implement sophisticated subgraph mocking | Doing so will allow us to deploy the entire app even though we are not able to access the subgraph yet. | #185 
Incorporate blacklist of RPCh nodes | RPCh nodes needs to be blacklisted from the reward computation. | #178 

## Definition of Done
- [x] Implement the communication logic between the EH and the metrics database.
- [x] Implement flexible budget splitting rule. 
- [x] Smaller feature improvements (computation/csv split, "too few" peers functionality, multiple peerID per safe address, RPCh nodes blacklisted)
- [x] Write unit tests for the new features.
