### ISSUE TITLE
Implement Subgraph functionality 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#185]
### Status Quo 

We mock the response of the subgraph: 
```python
def mock_data_subgraph(self):
        """
        Generates a dictionary that mocks the metrics received form the subgraph.
        :returns: a dictionary containing the data with safe stake addresses as key
                  and stake as value.
        """
        subgraph_dict = {
            "safe_1": {"stake": 10},
            "safe_2": {"stake": 55},
            "safe_3": {"stake": 23},
            "safe_4": {"stake": 85},
            "safe_5": {"stake": 62},
        }
        return subgraph_dict
```
### Task 
1. Implement the functionality of the actual subgraph by using, for example, the staking season 7 endpoint.  
2.  Fix the mock structure of the returned subgraph data 

### TODO 
Implement a more sophisticatted mocking of the subgraph. Essentially, construct a function that assignes a random stake to a given peer_id. That way we can test the 'ct-app' in staging even though the subgraph is missing. However, this makes sense once the DB connection for the economic handler gets implemented.

### Definition of Done 
- [x] Implement the functionallity of the subgraph
- [x] Fix moch data structure 
- [x] unittests the subgraph implementation
