### ISSUE TITLE
EconomicHandler improvements v2

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#204]
## Overview

This issue lists the upcoming tasks to be able to deploy the `EconomicHandler` (EH) to the staging environment. Therefore, combining it with the already running pieces in staging (`Aggregator`, `Netwatcher`, `Database`).

A complete structure overview can be found [here](https://github.com/hoprnet/ct-research/wiki/App-structure).

## Status Quo 

The EH runs locally and independently from the other parts of the `ct-app`.

## Tasks 

Task  | Description | Issue
 --- | --- | ---
Finish remaining tasks from EconomicHandler improvements epic | The remaining task concerns the communication of the economic handler with the database | #136
Generate tasks for the outgoing queue | Tasks for sending 1 HOP messages should be generated based on the expected reward calculation for each node. The amount of generated tasks for each `Postman` depends on the `expected_reward`, `ticket price` and `winning probability`. Currently, queue communication not included in the EH (not even mocked). | #219
Deploy the `EconomicHandler` | Deploy the economic handler in the staging environment. Currenty, the economic handler can only be executed locally as it is independent of the other modultes.  | ✅ 

## Definition of Done
- [x] Finish remaining tasks from EconomicHandler improvements epic
- [x] Generate tasks for the outgoing queue 
- [x] Deploy economic handler in staging
