### ISSUE TITLE
Netwatcher/Aggregator/AggTrigger/Database impovements v2

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#206]
### Overview
This issue lists the upcoming tasks that need to be addressed to have a fully deployed (on staging) and working environment for the next sprint.

A complete structure overview can be found [here](https://github.com/hoprnet/ct-research/wiki/App-structure).

### Tasks
Task  | Description | Issue
 --- | --- | ---
Switch to the new Python API structure | The API structure has recently changed and we still use the old structure. Even if it will change again before end of august, the structure will not change, and we can save a great effort by already transitioning to the new structure. For this, only the `HOPRNodeHelper` should be modified. | #220 
Implement the `Netwatcher`'s rolling-list sending strategy | `Netwatcher`s should not send their list every X minutes, but once a certain number of peers have been pinged, and send a list of constant size (exception on last sending is too old). This will make the `Netwatcher` task more asynchronous. | #231  
Define how the funding of channels will work | `Netwatcher`s are going to need some funds in the opened channels to be able to send 1 HOP messages through peers. Tino told us that "there will be a solution for it" (e.g. a plugin), but we don't know much about it or the current development progress of that feature | #269 
Describe the handling of successful and unsuccessful tasks | Tasks generated by the `EconomicHandler` are handled by the `Netwatcher`s. Failed delivery can be caused by many factors (NW down, peer not reachable, etc.) and we want to monitor those causes. Successful delivery still needs to be monitored. The task flow needs to be better defined for successful and un-successful message delivery. | [wiki](https://github.com/hoprnet/ct-research/wiki/Netwatcher-and-Postman)
Define the content of the `rewardTable` | The `rewardTable` is going to be used to store the state of message delivery. The actual content and structure of the table (columns) is not yet defined. | [wiki](https://github.com/hoprnet/ct-research/wiki/Database-and-tables)
Define the pace at which the `AggTrigger` triggers the sending to db | The `AggTrigger` triggers the `Aggregator` to send the formatted `peer-nodes` pairs to the `metricTable`. Currently, it wakes-up every couple of seconds. Before deploying code into production, this delay needs to be defined. | [wiki](https://github.com/hoprnet/ct-research/wiki/AggTrigger) 
Redirect failed tasks to an outgoing queue | When a NW is unable to complete a task and is the last possible NW for sending a message to the given peer, it should redirect the task to an outgoing queue (NW perspective). | #246 
Create task for successful message delivery | When a message delivery is successful, a task should be created in the outgoing queue so that the `EconomicHandler` can store this information in the `rewardTable`. | #246 
Deploy queues in staging | Queues implementation is ready, but not yet deployed into K8s. This implies testing the logic with the deployed broker beforehand. | #253 
Access the running `HOPRd` node from `Netwatcher`s in staging | `Netwatcher`'s are supposed to hit some deployed nodes API's. For now, only Pluto nodes have been tested, and the instances deployed are **not** hitting the API because the nodes available are not fully working. Once they will work, we need to hit their API. | #254 
Send remaining messages from next node in the list | The `send_1_hop_messages` task sends multiple messages to a peer. While sending, a node can go down. In this case, the sending of the remaining messages should be redirected to a different node. | #236 

### Definition of Done
- [x] `PythonAPIHelper` using the new API structure
- [x] `Netwatcher`'s rolling strategy implemented
- [x] Node funding documented
- [x] Handling of (un)successful tasks documented
- [x] Content of the `rewardTable` documented
- [x] Pace of the `AggTrigger` defined and implemented
- [x] Task created on failed message distribution (1 task for multiple messages)
- [x] Task created on successful message distribution (1 task for multiple messages)
- [x] Queues deployed in staging
- [x] `Netwatcher`'s and `Postman` hitting the deployed nodes' API
- [x] Remaining message to be sent transferred to the next node in line
