### ISSUE TITLE
Feature to store public files and make them downloadable 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#208]
### Overview

The `EconomicHandler` (EH) relies on reading and writing files:
- the EH needs to read a `parameter.json` file that defines the equations, parameters, budget, etc. for the reward calculation
- after calculating expected rewards, the EH outputs the results as a .csv file. The .csv file has two purposes: 
    - Someone can verify ex-post that the EH performed the reward calulation correctly.
    - The csv file can be used as a backup for airdropping tokens in case the distribution of tokens through the ct-app fails for some reason. 

*Note: Both the .json file and the .csv file do not contain any sensitive information. They can be public.*

A complete structure overview of the `ct-app` can be found [here](https://github.com/hoprnet/ct-research/wiki/App-structure).

### Task 
A Cloud Bucket is required to be able to store the .json file as well with the many .csv files that will be generated. 

Note that this approach relies on the developers code to perform that action. A guide on how to do that in python can be found [here](https://cloud.google.com/appengine/docs/legacy/standard/python/googlecloudstorageclient/read-write-to-cloud-storage?hl=de).

### Definition of Done 
- [ ] Cloud Bucket available (access credentials transmitted to the developers in order to use the feature)
- [ ] Reading .json file from Cloud Bucket
- [ ] Storing .csv files into Cloud Bucket
