### ISSUE TITLE
Visualize apy distribution and plot median apy 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#378]
### Current Situation 

We have plotted the average apy over time in Grafana.  

### Task 

 We need more insights about the `apy` as we are approaching a state where information about the apy gets more important. Therefore, the following is necessary: 

- [x] Renaming of APY to APR in documentation and code as we do not inlclude compunding of interest into the APY estimation. 
- [x] Plot the distribution of the APR in Grafana 
- [x] Plot the Median of the APR in Grafana

**Comment by jeandemeusy** [comment]
Ploting a line on top of an histogram is not possible in Grafana. Even showing the median value is not possible. However, in the legend of the graph, I have added the min, max and averages values
