### ISSUE TITLE
Update Economic Model in Wiki 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#379]
### Current Situation 

The description of the Economic Model on our wiki page must be updated. the reason being is that community members as well as HOPR employees are more and more interested in how the economic model works. 

### Task 

- [x] Update the description of the model.  
- [x] Describe the examples illustrating the mechanics of the model. 
- [x] Include the values of the parameters used for the distribution in production.

**Comment by MartinBenediktBusch** [comment]
Updated Model: https://github.com/hoprnet/ct-research/wiki/Economic-model
