### ISSUE TITLE
Automatically retrieve CT fundings

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-research#560]
To do an estimation of how much rewards were claimed by node runners, two values are needed: 
- how much CT funds were sent to CT safes. This can be retrieved by a SG to get current nodes safes funding from COMM safe. As we only use 1 safe now instead of 5, the fund sent to the old 4 safes needs to be added as a constant to the retrieve value from the SG.
- how much funds is remaining on CT nodes. This one is easy to get, as it's the sum of amount in safe plus amount in outgoing channels.

## Definition of Done
- [x] subgraph query written
- [x] provider created
- [x] funds retrieved from SG
- [x] constant value to be added set as a config value
