### ISSUE TITLE
Devops requirements of the first CT-dapp release  

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#58]
This epic tracks the devops requirements for the ct-dApp: 

- [ ] [Centralized monitoring](https://github.com/hoprnet/ct-research/issues/22)
- [ ] [Create a containerized testing environment](https://github.com/hoprnet/ct-research/issues/23)
- [ ] [Create a staging environment](https://github.com/hoprnet/ct-research/issues/24)
- [ ] [Have a static number of instances automatically deployed from a selected branch](https://github.com/hoprnet/ct-research/issues/25)
- [ ] [Create Alerts](https://github.com/hoprnet/ct-research/issues/27)
- [ ] [Centralized logging](https://github.com/hoprnet/ct-research/issues/28)
