### ISSUE TITLE
Financial Distribution Strategy 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#67]
# Task

Setup a financial distribution model that calculates the expected reward for each node in the network given its stake. The model should incorporate the following parameters: 

- total budget in HOPR for a given time period
- RPCh ticket price
- Number of packets the CT-dApp needs to output per second
- APY for node operators (for various sizes of nodes)
- Number of deployed CT-dApp instances
- Number of node runners

# Definition of Done 

1. [x] Setup the [financial distribution model](https://github.com/hoprnet/ct-research/wiki/Financial-distribution-strategy) according to the required parameters.  
2. [x] Present the distribution strategy to HOPR and get the confirmation to implement it. Parameters can be changed at any point in time.  
3. [x] Write a function that takes a dictionary of peer id's (keys) and their respective stake (value) as an input. The function should output a dictionary of peer id's as keys with the probabity to receive cover traffic and expected rewards as values.
