### ISSUE TITLE
Economic Model Improvement 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#83]
## Task 
- [ ] Implement transaction fees settlement cost on Gnosis chain as an output variable of the economic model. 
- [ ] Include the HOPR token price as an input parameter.  
- [ ] Simulate the expected ct-dApp output for a given combination of ticket price and winning probability that satisfies the settlement cost

## Problem 
If the USD amount for transaction fees on Gnosis Chain is much more than the HOPR tokens that users earn then the reward system is broken. 

Therefore, the ticket price needs to be high enough so that transaction fees do not eat-up expected rewards. One way to achieve this is via a combination of a higher ticket price then set by RPCh and a winning probability of <1. This is possible as the RPCh business case needs to make sense in expectation and not for every transaction.  

## Assumptions 

-  A ticket redemption event uses 15000 gas
- Gas prices on Gnosischain are 1e5 x 2e9/1e18 = $0.0002 per 100,000 gas.

**Comment by MartinBenediktBusch** [comment]
Closed because the issue is out of date
