### ISSUE TITLE
DevOps Requirements 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#84]
Find the current structure of the ct-dApp here: https://github.com/hoprnet/ct-research/wiki/dApp-structure

### metricTable 
A table is needed to store the peers detected by the netwatchers and filtered by an aggregator. The aggregator is going to input data from ~300 peers every 4hours (first approximation). The table can be emptied every 3month.

- [x] have a db table ready to store netwatcher_id, peer_id, metrics
- [x] will be accessed by Aggregator (writing) and by EconomicHandler (reading)
- [x] db should stay up at any cost (almost)

### rewardTable
A table is needed to store reward calculation result. This table will include almost as many entries as the metricTable.

- [x] have a db table ready to store peer_id, sent_reward
- [x] the table will be accessed by EconomicHandler (writing) and for monitoring purpose (reading)
- [x] db table can fail, but should be up again so that on the next iteration of EconomicHandler the missing db entries and the new entries can be added at the same time.

## Celery queues 
- [x] outgoing queue fillied by the economic handlers and read by the netwatchers 
- [x] incomming queue filled by the netwatcher instances and read by the economic handler

## grafana dashboards
- [x] need the connection form the metrics that the ct-dapp outputs to the dashboard (data visualizations will be done by us) 

### Aggregator
The aggregator is an instance (coded in Python) that will gather information multiple times per day from the NetWatchers and breaks connection conflicts. 

- [x] needs to run constantly with as few interruption as possible
- [x] has a connection port opened for POST request (logic already in the code)
- [x] should have a backup instance (exact copy of the one running) that takes over when the first one fails
- [x] will write to the metricTable

### NetWatcher
Multiple identical instances of Netwatcher are running at the same time. Each of them are sending regularly data to the aggregator via HTTP POST request.

- [x] deployment of X instances at the same time. We should have the ability to increase and decrease the amount of deployed nodes at any time. 
- [x] each instance communicates via HTTP POST request
- [x] each instance is bind to a HOPR node for network peer gathering

### EconomicHandler
The economic handler should run multiple times per day. It is a node in the network. It will query the metricTable to get the latest network state.
- [x] The instance should be up at anytime, but as it is only running some times per day, it can fail, as soon as it goes back up "quickly".

## Other

- [x] [Centralized monitoring](https://github.com/hoprnet/ct-research/issues/22)
- [x] [Create a containerized testing environment](https://github.com/hoprnet/ct-research/issues/23)
- [x] [Create a staging environment](https://github.com/hoprnet/ct-research/issues/24)
- [x] [Have a static number of instances automatically deployed from a selected branch](https://github.com/hoprnet/ct-research/issues/25)
- [x] [Create Alerts](https://github.com/hoprnet/ct-research/issues/27)
- [x] [Centralized logging](https://github.com/hoprnet/ct-research/issues/28)
